<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
			<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
            <link href="Backend/css-js/style.css" type="text/css" rel="stylesheet"/>
            <link rel="stylesheet" href="Backend/css-js/w3.css" type="text/css"/>
            <link rel="stylesheet" href="Backend/css-js/bootstrap.min.css" type="text/css"/>
			<script src="Backend/css-js/jquery.min.js" type="text/javascript"></script>
            <script src="Backend/css-js/bootstrap.min.js" type="text/javascript"></script>
            <title>LMPE.MA</title>
            <!--google maps scripts-->
            <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDnLu5Azr7UlYeD2hhJlpHjSSsU_BX3Mx8"></script>
			<script src="Backend/css-js/googlemaps.js" type="text/javascript"></script>